version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    ports:
      - 35432:5432
  backend:
    image: healthtech-backend:latest
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/postgres
      spring.datasource.password: password
      spring.datasource.username: postgres
    links:
      - postgres
    ports:
      - 8080:8081
#  vue:
#    image: healthtech-frontend:latest
#    depends_on:
#      - backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - '8081:8080'
volumes:
  pgdata:
    name: pgdata
